env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  require: true
  module: true
  __dirname: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
