name: Builds

on:
  pull_request:
    paths:
      - '**.ts'
      - '.github/workflows/**.yml'
  push:
    branches:
      - master
      - staging
    paths:
      - '**.ts'
      - '.github/workflows/**.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup deno!
        uses: actions/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install
      - run: deno task build
      - run: deno task lint
      - run: deno task test:coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
